// Auto-generated by: npx supabase gen types typescript --project-id <project-id> > src/types/supabase.ts
// Regenerate after each schema migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          role: "customer" | "admin";
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          role?: "customer" | "admin";
          created_at?: string;
        };
        Update: {
          full_name?: string | null;
          role?: "customer" | "admin";
        };
      };
      products: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          price_cents: number;
          currency: string;
          stock: number;
          image_url: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          price_cents: number;
          currency?: string;
          stock?: number;
          image_url?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          slug?: string;
          name?: string;
          description?: string | null;
          price_cents?: number;
          currency?: string;
          stock?: number;
          image_url?: string | null;
          active?: boolean;
        };
      };
      categories: {
        Row: { id: string; slug: string; name: string };
        Insert: { id?: string; slug: string; name: string };
        Update: { slug?: string; name?: string };
      };
      product_categories: {
        Row: { product_id: string; category_id: string };
        Insert: { product_id: string; category_id: string };
        Update: Record<string, never>;
      };
      carts: {
        Row: { id: string; user_id: string; created_at: string; updated_at: string };
        Insert: { id?: string; user_id: string; created_at?: string; updated_at?: string };
        Update: { updated_at?: string };
      };
      cart_items: {
        Row: {
          id: string;
          cart_id: string;
          product_id: string;
          quantity: number;
          unit_price_cents: number;
        };
        Insert: {
          id?: string;
          cart_id: string;
          product_id: string;
          quantity: number;
          unit_price_cents: number;
        };
        Update: { quantity?: number; unit_price_cents?: number };
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          status: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
          total_cents: number;
          currency: string;
          stripe_session_id: string | null;
          stripe_payment_intent_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
          total_cents: number;
          currency?: string;
          stripe_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
        Update: {
          status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
          stripe_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          quantity: number;
          unit_price_cents: number;
          product_snapshot: Json;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          quantity: number;
          unit_price_cents: number;
          product_snapshot: Json;
        };
        Update: Record<string, never>;
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          type: "shipping" | "billing";
          line1: string;
          line2: string | null;
          city: string;
          state: string;
          postal_code: string;
          country: string;
          is_default: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "shipping" | "billing";
          line1: string;
          line2?: string | null;
          city: string;
          state: string;
          postal_code: string;
          country?: string;
          is_default?: boolean;
        };
        Update: {
          type?: "shipping" | "billing";
          line1?: string;
          line2?: string | null;
          city?: string;
          state?: string;
          postal_code?: string;
          is_default?: boolean;
        };
      };
    };
    Functions: {
      create_order: {
        Args: {
          p_user_id: string;
          p_items: Json;
        };
        Returns: { order_id: string };
      };
    };
    Enums: {
      order_status: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
      user_role: "customer" | "admin";
    };
  };
};
